cmr:
  image: inspectit/cmr:1.6.7.79
  ports:
   - "8182:8182"
dvdstore:
  image: inspectit/dvdstore
  links:
   - cmr
  ports:
   - "8080:8080"
  environment:
   - AGENT_NAME=dvdstore
gui:
  image: inspectit/inspectit:1.6.7.79
  environment:
   - DISPLAY
   - XAUTHORITY=/.Xauth
  net: "host"
  volumes:
   - ${XAUTHORITY}:/.Xauth
